ibabygroup:
  swagger:
    enabled: false
  net:
    host: http://api.ibabygroup.cn/
  rest:
    host: http://10.45.237.58:18080/
    token: 2RRO7i13GqNryj3b
  appconfig:
    ignore-auth: true
spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.202:3306/doctor_voice?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 1234
#    type: com.zaxxer.hikari.HikariDataSource
  data:
    mongodb:
      host: 10.45.237.58
      port: 27017
      database: IMService
  imURL:
    usersig: eJxFkF1vgjAYhf8Lt1ukLeVrd0rMhOhAcVF60xSoo2NChx0Zmv33sUay2*fJm3POezP263TGpBQlZYpaXWk8GcB41Jh-S9Fxyk6KdyOGtm0jACbb8*4i2mYUCEAbIguAfylK3ihxEvpQ5Cwf7uIi3kayWWZBuA3S82u8zxbSrxOyW*btXKGFV5qfq9AhL6lbgSS4ZlWzjo-bsJpHxYF4vsfNh8ivD1dZrQjvIz-un3cDtnBC3j9M2HpduPGmsLKmettfezy2g9h38F0qceaau66DMHAnzoqi-WoUVYPk*hk-vyHrVpU_
    identifier: ibaby
    sdkappid: 1400014964
    privStr: |
             -----BEGIN PRIVATE KEY-----
             MIGEAgEAMBAGByqGSM49AgEGBSuBBAAKBG0wawIBAQQgrST5Cp0xqvrZH3eeCUJa
             fpCZkZtMiE8FTZRf+QwGDJuhRANCAARsE2+zvnRysR6eC/HNPZ/xA8a5m3OKLt1K
             lyWsa7IWZR7VFR1DGDm49VppLUrZ0HothhS++d3ZDQiaVAEkKvCr
             -----END PRIVATE KEY-----
    pubStr: |
            -----BEGIN PUBLIC KEY-----
            MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEbBNvs750crEengvxzT2f8QPGuZtzii7d
            SpclrGuyFmUe1RUdQxg5uPVaaS1K2dB6LYYUvvnd2Q0ImlQBJCrwqw==
            -----END PUBLIC KEY-----
  rabbitmq:
    host: 10.45.237.58
    port: 5672
    username: ibaby
    password: ShareIbaby2015
    virtual-host: /im
# redis
redis:
  host: 10.45.237.58
  port: 6380
  password: shareibaby160
  database: 10
  pool:
    max-idle: 8
    min-idle: 0
    max-active: 10
    max-wait: -1
# nginx
app-uac-server-prod:
 ribbon:
  listOfServers: 10.144.45.27:9696
